# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

_SNAKE_TO_CAMEL_CASE_TABLE = {
    "connect_timeout": "connectTimeout",
    "database_username": "databaseUsername",
    "expected_version": "expectedVersion",
    "max_connections": "maxConnections",
    "ssl_mode": "sslMode",
}

_CAMEL_TO_SNAKE_CASE_TABLE = {
    "connectTimeout": "connect_timeout",
    "databaseUsername": "database_username",
    "expectedVersion": "expected_version",
    "maxConnections": "max_connections",
    "sslMode": "ssl_mode",
}
